### ISSUE TITLE
diycode 访问好慢

### ISSUE THREAD

**Issue by jp1017** [D-clock/AndroidStudyCode#2]
还是这里好玩 :smile:

**Comment by D-clock** [comment]
@jp1017 谢谢支持哈，diycode还在继续完善，请问你在什么地区，用的是什么网络进行访问呢？

**Comment by jp1017** [comment]
青岛 移动 lantern

**Comment by D-clock** [comment]
@jp1017 好滴，稍候我们这边测速试试看，感谢反馈哈！欢迎多上来diycode玩耍！

**Comment by jp1017** [comment]
![3](https://cloud.githubusercontent.com/assets/7868514/15530278/11634f4c-2286-11e6-83f2-e0efd5569042.jpg)

界面根本没法看。。

**Comment by jp1017** [comment]
这是你自己的东西吗，大大求带， :sos: :+1: :wave: :smile:

**Comment by D-clock** [comment]
@jp1017 啊。。。求带倒是不敢啊。。。多少来一起玩耍，互相交流进步吧！

**Comment by D-clock** [comment]
与本库无关！
