### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by TommyLemon** [D-clock/AndroidStudyCode#4]
Plugin with id "com.android.application" not found

**Comment by D-clock** [comment]
@TommyLemon Hello，已经修复此问题，同步最新代码，详细内容参加README :smile:

**Comment by TommyLemon** [comment]
还是一样的问题啊，重新下载了、也用sourcetree拉取了，不管是open还是import都一样

**Comment by TommyLemon** [comment]
@D-clock

**Comment by TommyLemon** [comment]
解决了
http://stackoverflow.com/questions/26750404/android-studio-error3-0-plugin-with-id-com-android-application-not-found?newreg=8cdfa6c488684d3db0a5509f5d8f43de

**Comment by D-clock** [comment]
ok，good！之前我有个配置存在问题，所以更新了一下！搞定就好！
