### ISSUE TITLE
未指定存储目录

### ISSUE THREAD

**Issue by TommyLemon** [D-clock/AndroidStudyCode#6]
模拟器Nexus6P 6.0 
点击“拍张照片吧”，没有拍照，只显示 “未指定存储目录”

**Comment by D-clock** [comment]
@TommyLemon ok，我跟进一下！ :smile:

**Comment by TommyLemon** [comment]
@D-clock 刚用nexus5 6.0.1真机测试出现同样的问题

**Comment by ghost** [comment]
怎么解决啊

**Comment by TommyLemon** [comment]
@dingwanshun 
这个在nexus5(6.0.1)及其它多款各品牌（三星华为小米魅族oppo酷派）6.0以下版本的机器上测试通过
https://github.com/TommyLemon/Android-ZBLibrary/blob/master/ZBLibrary(ADT)/ZBLibrary/src/zuo/biao/library/ui/SelectPictureActivity.java

**Comment by ghost** [comment]
@TommyLemon 谢谢。我来试试

**Comment by D-clock** [comment]
@TommyLemon @dingwanshun Android M 开始的 RuntimePermission问题，已经处理。最近工作忙，耽搁太久，不好意思！
