### ISSUE TITLE
深入理解Android中的Matrix.md中图的标注有误

### ISSUE THREAD

**Issue by van048** [D-clock/AndroidStudyCode#8]
应该是前面是postTranslate，后面是preTranslate

**Comment by D-clock** [comment]
@van048 最后一张图有点错误，晚上回家再改，谢谢提醒

**Comment by van048** [comment]
而且这个矩阵乘不起来的。。。

**Comment by D-clock** [comment]
@van048 嗯，我指的是矩阵乘不起来的错误，但是前面应该是preTranslate，后面试postTranslate没错吧！

**Comment by van048** [comment]
@D-clock 应该是这样的，参数对应的Matrix其实是一个单位矩阵
![qq 20160720111618](https://cloud.githubusercontent.com/assets/4905360/16974080/987a50b4-4e6b-11e6-88d4-5fc245d4e5be.jpg)

**Comment by D-clock** [comment]
@van048 确认了一下，确实我弄错了哈，尴尬。数学上的左乘、右乘：

> pre-multiply（A.premult(B)==B_A，即B左乘A）
> post-multiply（A.postmult(B)==A_B，即B右乘A）

被我下意识的放入到 pre、post函数中去了，然后去开发者文档仔细看看确认了一下，确实如你所言：

preTranslate：Preconcats the matrix with the specified translation. M' = M \* T(dx, dy)
postTranslate：Postconcats the matrix with the specified translation. M' = T(dx, dy) \* M

非常感谢你指出，我要去更正一下才行！

**Comment by van048** [comment]
@D-clock 是的，我一开始也混淆了数学概念与android概念了
