### ISSUE TITLE
some problems

### ISSUE THREAD

**Issue by LinXiaoTao** [D-clock/AndroidStudyCode#9]
Matrix multiplication is not commutative law,How can I guarantee the changes as expected?
for example, the first call postTranslate, then call postRotate. If reversed, the result is completely different.
thanks

**Comment by van048** [comment]
In your example, it will execute in this order: translate->rotate. Remember that rotation is based on the origin, not the center point of itself. Thus the result (the final coordinate of each point) is different in most cases. You should first make sure your transform is right before coding.

**Comment by LinXiaoTao** [comment]
For example, these two codes have different results:
1.mMatrix.postTranslate (100, 100);
    mMatrix.postRotate (30);
2.mMatrix.postRotate (30);
    mMatrix.postTranslate (100, 100);
know I can to get the desired effect?
thanks

**Comment by van048** [comment]
@LinXiaoTao It depends on what you desire....

**Comment by LinXiaoTao** [comment]
I just think that reversing the order will produce different results,Intuitive difficult to achieve
